language: go

go:
  - 1.12.5

env:
- GO111MODULE=on

script:
    - go install github.com/golang/mock/mockgen
    - make build
    - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 2cc83759-e383-4420-a1ff-4f11d4be99d9