version: '3'
services:
  broker1:
    image: centos:latest
    container_name: lindb_broker1
    command: /usr/bin/lind broker run --config /lindb/configs/broker1.toml
    volumes:
      - $PWD/../bin/lind-linux:/usr/bin/lind
      - $PWD:/lindb
    depends_on:
      - etcd
    links:
      - etcd
    ports:
      - "9000:9000"
  storage1:
    image: centos:latest
    container_name: lindb_storage1
    command: /usr/bin/lind storage run --config /lindb/configs/storage1.toml
    volumes:
      - $PWD/../bin/lind-linux:/usr/bin/lind
      - $PWD:/lindb
    depends_on:
      - etcd
      - broker1
    links:
      - etcd

  broker2:
    image: centos:latest
    container_name: lindb_broker2
    command: /usr/bin/lind broker run --config /lindb/configs/broker2.toml
    volumes:
      - $PWD/../bin/lind-linux:/usr/bin/lind
      - $PWD:/lindb
    depends_on:
      - etcd
    links:
      - etcd
  storage2:
    image: centos:latest
    container_name: lindb_storage2
    command: /usr/bin/lind storage run --config /lindb/configs/storage2.toml
    volumes:
      - $PWD/../bin/lind-linux:/usr/bin/lind
      - $PWD:/lindb
    depends_on:
      - etcd
      - broker2
    links:
      - etcd

  broker3:
    image: centos:latest
    container_name: lindb_broker3
    command: /usr/bin/lind broker run --config /lindb/configs/broker3.toml
    volumes:
      - $PWD/../bin/lind-linux:/usr/bin/lind
      - $PWD:/lindb
    depends_on:
      - etcd
    links:
      - etcd
  storage3:
    image: centos:latest
    container_name: lindb_storage3
    command: /usr/bin/lind storage run --config /lindb/configs/storage3.toml
    volumes:
      - $PWD/../bin/lind-linux:/usr/bin/lind
      - $PWD:/lindb
    depends_on:
      - etcd
      - broker3
    links:
      - etcd

  etcd:
    image: bitnami/etcd
    container_name: lindb_etcd
    environment:
      ETCD_NAME: etcd
      ETCD_DATA_DIR: /tmp/etcd-data
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: etcd=http://etcd:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: my-etcd-token
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ALLOW_NONE_AUTHENTICATION: "yes"

