name: Go
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Test
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        make test
        bash <(curl -s https://codecov.io/bash) -t 571f35bb-4929-4ac5-88cd-8d2c21302b40

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        make build
